### ISSUE TITLE
May i write a blog in Chinese about your talk at Android Meetup 3/31

### ISSUE THREAD

**Issue by bearprada** [bkase/cyklic#1]
sorry for asking this kind of question through the Github issues.

I like your talk so much, it made my development life easier.

**Comment by bkase** [comment]
No problem -- yes please write the blog post!

**Comment by bearprada** [comment]
blog is here 
https://medium.com/@pradabear/android-meetup-in-san-fransisco-e1e8dde1554c#.a1znzosxs
thanks for your sharing in the android meetup. it helps me a lot :>
